### ISSUE TITLE
Unable to login externally to universe, browser error "Login failed (reason 471)"

### ISSUE THREAD

**Issue by Cosmica2** [ChrisMiuchiz/awtools#3]
Hi there Chris, so far awtools has worked flawlessly on any internal home network PC. However when clients are attempting to connect externally it gives them error "Login failed (reason 471)" where 471 just means "disconnected" according to some definitions I found. I've enabled trace log and am unable to find a difference between a successful and unsuccessful connection other than a sudden Disconnect after reading the login AWPacket (with username, password, etc) and doesn't allow clients to continue past the login screen.

Clients can see the server, it will give errors I've tested such as "invalid username" or "this user already in use" so clients appear to be connecting just won't launch the browser. I've attempted setting the IP to 0.0.0.0 and 192.168 address. It won't accept any external IP address within the universe.toml file (from what I've read that's by design with rust). Any help would be greatly appreciated.

**Comment by ChrisMiuchiz** [comment]
471 is an error code with deliberately deceptive [documentation](http://wiki.activeworlds.com/index.php?title=SDK_Reason_Codes). Most of the time, if not all of the time, it actually refers to failed Universe license verification. That is why AW's documentation is deliberately deceptive.

Prior to AW::Browser 1701 (7.0), Universe operators were provided with license information that was encrypted with AW Inc.'s private RSA key, and both the Universe server and the AW browsers would use the public key to validate the information. In theory, this stops unmodified AW browsers from connecting to unauthorized or third-party Universe servers, giving reason code 471 instead. In practice, this is no longer true since this project contains their private RSA key.

However, the mechanism still enforces some restrictions on how any AW Universe server can be used. Here is the struct used for representing the unencrypted Universe license from `aw_core/src/reg_lic.rs`:
```rust
pub struct AWRegLicData {
    license_version: u32,
    ip_address: [u8; 4],
    port: u32,
    land_limit: u32,
    max_users: u32,
    world_limit: u32,
    expiration_time: i32,
    major_version: u16,
    minor_version: u16,
    name: [u8; 0x20],
    can_have_bots: u32,
}
```
Pertinent to this issue are the IP address and port, which the browser validates to ensure the Universe it is connecting to is at the authorized address and port. This Universe server generates licenses on-the-fly to send to connecting browsers, so operators do not need to directly worry about generating them. However, the Universe server needs to know what IP address and port browsers will be connecting to in order to provide them with a valid Universe license. This is why the following line is in the Universe's README:

`The IP address of the Universe server in universe.toml must be the same as the IP address that incoming clients will connect to.`

**An internet-facing server should be directly connected to the internet (not behind NAT on a home network)** and then they will be able to bind to an external address provided in `universe.toml`. If you really want to circumvent that, you could modify `universe/src/universe_license.rs:LicenseGenerator::create_license_data` to create licenses with the specific IP address that you want. It is a bad idea to do this because your World server(s) will likely be on that network too, so a Universe server will tell external browsers to connect to worlds at a private address (e.g. 192.168.#.#) and they will be unable to reach those worlds. That issue affects first-party Universe servers as well.

What you described is expected behavior for any instance where a browser connects to a Universe server using an IP address other than the one the Universe server has been provided in its `universe.toml`.

**Comment by ChrisMiuchiz** [comment]
I have made an experimental commit that allows you to separately specify the licensed IP address and the bound IP address.

https://github.com/ChrisMiuchiz/awtools/commit/706b57dd5e13abc4c65d05460b36a9f3e45d1246

This will allow you to bind to 0.0.0.0 while providing licenses for the IP address you expect clients to connect to, if you want. Keep in mind that there will still only be 1 IP address that clients will be able to authenticate with, and that is the one specified by `license_ip`.

**Comment by Cosmica2** [comment]
Excellent! Thank you very much Chris, this did the trick. I appreciate the explanation prior as well. This now works perfectly with an external-facing IP, as well as those who wish to still use an internal-only IP I also tested. The only caveat, as you mentioned above, it appears the world server is unable to accept connections from internal clients if ran on the same server. The clients, uni server and world server must all be external to each other is only way I've gotten to work properly myself. This could be by design for all.

I'll keep retrying to see if there's a way I'm missing to consolidate. For now I consider this issue/request resolved. Cheers!!!

P. S. It would humble me to donate for your time, I wasn't sure how to reach you privately will search around. Thanks!
